name: SBB
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.8
  - pytorch~=1.10.1
  - pyro-ppl~=1.8.0
  - matplotlib~=3.5.1
  - pandas~=1.3.5
  - python-graphviz~=0.19.1
  - scikit-learn~=1.0.2
  - nltk~=3.6.5
  - tqdm
  - jupyter
  - jupyterlab
  - pip>=21.1.2
  - pip:
      - funsor~=0.4.2
      - tweet-preprocessor~=0.6.0